print_info() {
    info title

    info " " distro
    info "󰍛 " memory
    info " " wm
    info "󰣖 " term
    info "󰔚 " uptime
    info "󰏗 " packages
}

title_fqdn="off"
distro_shorthand="on"
os_arch="off"
uptime_shorthand="tiny"
memory_unit="gib"

# Custom ASCII art
image_backend="ascii"
image_source="/Users/clementomnes/.config/neofetch/ascii.txt"

# Style
bold="off"
underline_enabled="off"
separator=" "
color_blocks="off"

# Disable extra info
cpu_display="off"
gpu_display="off"
battery_display="off"
disk_display="off"
